apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-playground-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-playground
  template:
    metadata:
      labels:
        app: api-playground
        version: 1.1.3-1
    spec:
      containers:
      - name: api-playground
        image: gcr.io/api-playground-238304/api-playground