apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-playground-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-playground
  template:
    metadata:
      labels:
        app: api-playground
        version: 2.0.0
    spec:
      containers:
        - name: api-playground
          image: gcr.io/api-playground-245105/api-playground
          # env:
          #   - name: JWT_SECRET
          #     valueFrom:
          #       secretKeyRef:
          #         name: api-playground
          #         key: JWT_SECRET
          #   - name: AWS_SECRET_ACCESS_KEY
          #     valueFrom:
          #       secretKeyRef:
          #         name: api-playground
          #         key: JWT_SECRET
          #   - name: AWS_ACCESS_KEY_ID
          #     valueFrom:
          #       secretKeyRef:
          #         name: api-playground
          #         key: AWS_ACCESS_KEY_ID
